name: hiki
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1
environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  async: ^2.8.2
  collection: ^1.16.0
  cupertino_icons: ^1.0.2
  dio: ^4.0.4
  flutter:
    sdk: flutter
  flutter_image: ^4.1.4
  flutter_map: ^2.2.0
  flutter_web_browser: ^0.17.1
  geocoding: ^2.0.5
  geolocator: ^9.0.2
  get: ^4.6.5
  google_fonts: ^3.0.1
  http: ^0.13.5
  latlong2: ^0.8.1
  meta: ^1.7.0
  path: ^1.8.0
  persistent_bottom_nav_bar: ^4.0.2
  positioned_tap_detector_2: ^1.0.4
  proj4dart: ^2.1.0
  shared_preferences: ^2.0.12
  sqflite: ^2.0.2
  transparent_image: ^2.0.0
  tuple: ^2.0.1
  vector_math: ^2.1.2


dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
